# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dust25', models.IntegerField()),
                ('dust100', models.IntegerField()),
                ('temp', models.FloatField()),
                ('humid', models.IntegerField()),
                ('discomfort_index', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('device_id', models.CharField(max_length=100)),
            ],
        ),
    ]
